name: build-packages

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}-${{ matrix.branch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-25.12
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: verify downgrade compatibility
        run: bash .github/scripts/verify-compatibility.sh

      - name: build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: nikki
          PACKAGES: luci-app-nikki
          NO_REFRESH_CHECK: true

      - name: verify packages
        run: bash .github/scripts/verify-packages.sh "bin/packages/${{ matrix.arch }}/nikki"

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: nikki_${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/nikki
